FROM alpine:latest
LABEL maintainer="Ferdinand Prantl <prantlf@gmail.com>"
RUN cd /root && \
	wget https://www.neonious.com/lowjs/downloads/lowjs-linux-x86_64-20200525_59c0757.tar.gz && \
	tar xf lowjs-linux-x86_64-20200525_59c0757.tar.gz && \
	rm lowjs-linux-x86_64-20200525_59c0757/LICENSE lowjs-linux-x86_64-20200525_59c0757/README.md && \
	cp -r lowjs-linux-x86_64-20200525_59c0757/* /usr/local/ && \
	rm -r lowjs-linux-x86_64-20200525_59c0757*
WORKDIR /root
EXPOSE 80 443
ENTRYPOINT ["/usr/local/bin/low"]
CMD ["-h"]
